### ISSUE TITLE
hardcoded modal width too large for mobile phones

### ISSUE THREAD

**Issue by jcchin** [mizzao/meteor-tutorials#8]
On smaller phones, the default modal stretches beyond the device width. I'll submit a PR to shrink it if (device width) < 560px

**Comment by malcolmevans** [comment]
Hi there @jcchin ! Did you ever find a solution for this issue?

Thanks!

**Comment by mizzao** [comment]
#7 is merged into master and will be out in the next version. Please test if you are interested.
