### ISSUE TITLE
Question: can I use this with other bootstrap package ?

### ISSUE THREAD

**Issue by willemx** [mizzao/meteor-tutorials#9]
I would like to use this nice package in my project, but I don't want to include twbs:bootstrap because I am already using nemo64:bootstrap less. What would be the best way to accomplish this?

**Comment by mizzao** [comment]
I just pushed a version (`0.6.6`) that only uses weak dependencies, so you can choose which bootstrap package you'd like to use. Let me know if this works for you.

**Comment by willemx** [comment]
Yes, it works.
Thanks!!!
